import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Geist, Geist_Mono } from 'next/font/google';

import CursorParticles from '@/components/CursorParticles';
import WriteLinkButton from '@/components/WriteLinkButton';
import { MusicProvider } from '@/contexts/MusicProvider';
import TanstackQueryLayout from '@/layouts/TanstackQueryLayout';

import type { Metadata } from 'next';

import 'highlight.js/styles/atom-one-dark.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}>
        <CursorParticles />
        <TanstackQueryLayout>
          <MusicProvider>
            {children}
            <WriteLinkButton />
          </MusicProvider>
        </TanstackQueryLayout>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
